-- 코드를 입력하세요
SELECT 
    CAR_ID, 
    C.CAR_TYPE, 
    FLOOR(DAILY_FEE * (100 - DISCOUNT_RATE) * 0.01 * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    ON C.CAR_TYPE = P.CAR_TYPE
WHERE 
    CAR_ID NOT IN(
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE NOT (START_DATE > "2022-11-30" OR END_DATE < "2022-11-01")
    ) 
    AND C.CAR_TYPE IN("세단", "SUV") 
    AND DURATION_TYPE LIKE "30%"
    AND 500000 <= (DAILY_FEE * (100 - DISCOUNT_RATE) * 0.01 * 30) 
    AND (DAILY_FEE * (100 - DISCOUNT_RATE) * 0.01 * 30) < 2000000
ORDER BY
    FEE DESC,
    CAR_TYPE ASC,
    CAR_ID DESC