# -- 코드를 입력하세요
SELECT O.FOOD_TYPE, O.REST_ID, O.REST_NAME, O.FAVORITES
FROM REST_INFO O
WHERE (O.FOOD_TYPE, O.FAVORITES) IN (
    SELECT I.FOOD_TYPE, MAX(I.FAVORITES)
    FROM REST_INFO I
    GROUP BY FOOD_TYPE 
    )
ORDER BY FOOD_TYPE DESC