-- 코드를 입력하세요

#SELECT *
#FROM ICECREAM_INFO

#SELECT *
#FROM FIRST_HALF;

SELECT A.FLAVOR
FROM ICECREAM_INFO AS A
INNER JOIN FIRST_HALF AS B
ON A.FLAVOR = B.FLAVOR
WHERE B.TOTAL_ORDER > 3000 AND INGREDIENT_TYPE = 'fruit_based'
ORDER BY B.TOTAL_ORDER DESC