-- 코드를 입력하세요
SELECT BOARD_ID, WRITER_ID, TITLE, PRICE, replace(replace(replace(STATUS, "DONE", "거래완료"), "SALE", "판매중"), "RESERVED", "예약중") AS STATUS
FROM USED_GOODS_BOARD
WHERE CREATED_DATE = "2022-10-05"
ORDER BY BOARD_ID DESC