-- 코드를 입력하세요
SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*)
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY O
WHERE YEAR(START_DATE) = 2022 AND MONTH(START_DATE) BETWEEN 8 AND 10
GROUP BY MONTH, CAR_ID
HAVING (
    SELECT COUNT(*)
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY I
    WHERE YEAR(START_DATE) = 2022 AND MONTH(START_DATE) BETWEEN 8 AND 10
    GROUP BY CAR_ID
    HAVING O.CAR_ID = I.CAR_ID
) >= 5
ORDER BY MONTH ASC, CAR_ID DESC