-- 코드를 작성해주세요
SELECT ID, 
    CASE
        WHEN TILE = 1 THEN "CRITICAL"
        WHEN TILE = 2 THEN "HIGH"
        WHEN TILE = 3 THEN "MEDIUM"
        WHEN TILE = 4 THEN "LOW"
    END AS COLONY_NAME
FROM (
    SELECT ID, NTILE(4) OVER(ORDER BY SIZE_OF_COLONY DESC) AS TILE
    FROM ECOLI_DATA
) AS A
ORDER BY ID ASC

# SELECT ID, NTILE(4) OVER(ORDER BY SIZE_OF_COLONY DESC) AS TILE
#     FROM ECOLI_DATA