-- 코드를 입력하세요
SELECT floor(PRICE / 10000) * 10000 AS PRICE_GROUP, count(*) AS PRODUCTS
FROM PRODUCT
GROUP BY PRICE_GROUP
ORDER BY PRICE_GROUP ASC
# SELECT *, round(PRICE / 10000, 0)
# FROM PRODUCT
# ORDER BY price asc