-- 코드를 입력하세요
SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(BOOK_TOTAL_SALES) AS TOTAL_SALES
FROM
    (SELECT *, SUM(SALES) * PRICE AS BOOK_TOTAL_SALES
    FROM BOOK B
        JOIN AUTHOR A
        USING(AUTHOR_ID)
        JOIN BOOK_SALES S
        USING(BOOK_ID)
    WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
    GROUP BY B.BOOK_ID) S
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY
    AUTHOR_ID ASC,
    CATEGORY DESC

# SELECT *, SUM(SALES) * PRICE AS TOTAL_SALES
#     FROM BOOK B
#         JOIN AUTHOR A
#         USING(AUTHOR_ID)
#         JOIN BOOK_SALES S
#         USING(BOOK_ID)
#     WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
#     GROUP BY BOOK_ID