-- 코드를 입력하세요
SELECT DISTINCT CAR_ID,
    CASE
        WHEN
        CAR_ID IN(
            SELECT DISTINCT CAR_ID
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
            WHERE "2022-10-16" BETWEEN start_date AND end_date
            ORDER BY CAR_ID DESC
        )
        THEN "대여중"
        ELSE "대여 가능"
        END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
ORDER BY CAR_ID DESC

# SELECT *
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# ORDER BY CAR_ID DESC