-- 코드를 입력하세요
SELECT
    HISTORY_ID,
    FLOOR(DAILY_FEE * (100 - IFNULL(DISCOUNT_RATE, 0)) * 0.01 * RENTAL_DATE) AS FEE
FROM 
    (
        SELECT 
            *,
            CASE
                WHEN 7 <= DATEDIFF(END_DATE, START_DATE) AND DATEDIFF(END_DATE, START_DATE) < 30
                THEN '7일 이상'
                WHEN 30 <= DATEDIFF(END_DATE, START_DATE) AND DATEDIFF(END_DATE, START_DATE) < 90
                    THEN '30일 이상'
                WHEN 90 <= DATEDIFF(END_DATE, START_DATE)
                    THEN '90일 이상'
            END AS DURATION,
            DATEDIFF(END_DATE, START_DATE) + 1 AS RENTAL_DATE
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    ) AS H
    JOIN CAR_RENTAL_COMPANY_CAR C
    ON H.CAR_ID = C.CAR_ID
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
    ON C.CAR_TYPE = D.CAR_TYPE AND H.DURATION = DURATION_TYPE
WHERE C.CAR_TYPE = "트럭"
ORDER BY
    FEE DESC,
    HISTORY_ID DESC

# SELECT
#     CASE
#         WHEN 7 <= DATEDIFF(END_DATE, START_DATE) AND DATEDIFF(END_DATE, START_DATE) < 30
#         THEN 7
#         WHEN 30 <= DATEDIFF(END_DATE, START_DATE) AND DATEDIFF(END_DATE, START_DATE) < 90
#             THEN 30
#         WHEN 90 <= DATEDIFF(END_DATE, START_DATE)
#             THEN 90
#     END
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 