-- 코드를 작성해주세요
SELECT C.ITEM_ID, C.ITEM_NAME, C.RARITY
FROM ITEM_INFO P
    JOIN ITEM_TREE T ON P.ITEM_ID = T.PARENT_ITEM_ID
    JOIN ITEM_INFO C ON T.ITEM_ID = C.ITEM_ID
WHERE P.RARITY = "RARE"
ORDER BY C.ITEM_ID DESC

