-- 코드를 입력하세요
#SELECT avg(REVIEW_SCORE)
#FROM REST_REVIEW
#GROUP BY REST_ID
SELECT RI.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS, round(avg(RR.REVIEW_SCORE), 2) as SCORE
FROM REST_INFO AS RI
JOIN REST_REVIEW AS RR
ON RR.REST_ID = RI.REST_ID
WHERE RI.ADDRESS LIKE "서울%"
GROUP BY RI.REST_ID
ORDER BY avg(RR.REVIEW_SCORE) DESC, RI.FAVORITES DESC